### ISSUE TITLE
Being able to use Tradingview strategies with JRR

### ISSUE THREAD

**Issue by Me4tGrind3r** [rapmd73/JackrabbitRelay#15]
I would like to request the feature that JRR can reviece signals from TV when using strategies.
The TV strategy may send  in it's webhook payload:
 "Exchange":"ftx","Market":"Future","Account":"003sniperatrmacdma","Action":"{{strategy.order.action}}","Asset":"BTC/USD:USD","Base":"{{strategy.order.contracts}}" }
 
 {{strategy.order.action}} = buy or sell
 {{strategy.order.contracts}} = amount to buys or sell as Base value ( 0.00001 BC)
 
 The strategy itself will long/short; stop loss; multi take profit etc. and the strategy properties (Initial capital; Base currency; Order size settings) will be used internaly for these calculations.
 
 All what JRR will recieve in the final payload is buy/sell from the {{strategy.order.action}} and correct order amount as base value from {{strategy.order.contracts}} (Settings on TV strategy in USD will result in the correct signal for base amount automatically right now) 
 
 I "think" what would be the final request is:
 
 - Please let JRR long and short with the buy/sell signal from TV strategies (at this time sell can not short)
 - Please let JRR understand base values from TV strategies (at this time base will only make a minimum order ( 1 Lot))
 
 
 I use FTX PERPS with it.
 Testaccount can be provided
 Best regards,
 Me4tgrinder

**Comment by rapmd73** [comment]
This should be functional. Please retest with the TVstrategy item set to yes.

Something like thin you your payload:

"TVstrategy":"Yes",

Pleaswe be sure to also use,

"RemapSymbol":"Yes",

to remap the ticker macro to your proper ecxhange ID.

Thenk you.

**Comment by Me4tGrind3r** [comment]
It is working flawlessly, Thank you!
